export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const ADD_COMPLETED = 'ADD_COMPLETED';
export const REMOVE_COMPLETED = 'REMOVE_COMPLETED';
export const DELETE_COMPLETED = 'DELETE_COMPLETED';
